name = "Andes"
uuid = "93a26e3f-343a-4ab9-b467-a68c67574964"
authors = ["Hantao Cui <hcui7@utk.edu>"]
version = "0.2.0"

[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
PyCall = "1.93"
Conda = "1.7"
Pkg = "1.7"
julia = "1"
SparseArrays = "0.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
